"""
PDF export for ARIA reports.

Converts Markdown report content to a styled PDF using reportlab.
Falls back to plain-text if reportlab is not available.
"""
import io
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from db.session import get_db
from db.models import Report

router = APIRouter(tags=["export"])


def _markdown_to_pdf_bytes(title: str, domain: str, content: str, created_at: datetime) -> bytes:
    """Convert report content to a styled PDF.

    Uses reportlab for PDF generation with professional formatting.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    except ImportError:
        raise HTTPException(
            status_code=501,
            detail="PDF export requires 'reportlab' package. Install with: pip install reportlab"
        )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=18,
        textColor=HexColor("#1a1a2e"),
        spaceAfter=6,
    )
    meta_style = ParagraphStyle(
        "ReportMeta",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#666666"),
        spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "ReportHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=HexColor("#16213e"),
        spaceBefore=14,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "ReportBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=15,
        textColor=HexColor("#333333"),
        spaceAfter=8,
    )
    bullet_style = ParagraphStyle(
        "ReportBullet",
        parent=body_style,
        leftIndent=20,
        bulletIndent=10,
        spaceAfter=4,
    )

    story = []

    # Title
    story.append(Paragraph(f"ARIA Intelligence Report", title_style))
    story.append(Paragraph(
        f"Domain: {domain.upper()} | Generated: {created_at.strftime('%B %d, %Y at %H:%M UTC')}",
        meta_style
    ))
    story.append(Spacer(1, 10))

    # Parse markdown-ish content into paragraphs
    for line in content.split("\n"):
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 6))
            continue

        # Headings
        if stripped.startswith("## "):
            text = stripped[3:].strip()
            story.append(Paragraph(text, heading_style))
        elif stripped.startswith("# "):
            text = stripped[2:].strip()
            story.append(Paragraph(text, title_style))
        # Bullet points
        elif stripped.startswith("- ") or stripped.startswith("* "):
            text = stripped[2:].strip()
            # Simple bold handling
            text = text.replace("**", "<b>", 1).replace("**", "</b>", 1)
            story.append(Paragraph(f"• {text}", bullet_style))
        # Regular paragraph
        else:
            text = stripped.replace("**", "<b>", 1).replace("**", "</b>", 1)
            story.append(Paragraph(text, body_style))

    # Footer
    story.append(Spacer(1, 30))
    footer_style = ParagraphStyle(
        "Footer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#999999"),
    )
    story.append(Paragraph(
        "Generated by ARIA — Autonomous Research & Intelligence Agent",
        footer_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


@router.post("/reports/{report_id}/export")
async def export_report_pdf(
    report_id: uuid.UUID,
    db: AsyncSession = Depends(get_db),
):
    """Export a report as a styled PDF document."""
    result = await db.execute(
        select(Report).where(
            Report.id == report_id,
            Report.is_deleted == False,
        )
    )
    report = result.scalar_one_or_none()
    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    pdf_bytes = _markdown_to_pdf_bytes(
        title=report.query,
        domain=report.domain,
        content=report.content or "",
        created_at=report.created_at,
    )

    # Generate filename
    safe_query = "".join(c if c.isalnum() or c in " -_" else "" for c in report.query)[:50]
    filename = f"ARIA_Report_{safe_query}_{report.domain}.pdf"

    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )
