"""add share_token and is_deleted to reports

Revision ID: 706405861e01
Revises: eb2bf8102413
Create Date: 2026-03-02 20:47:45.991651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706405861e01'
down_revision: Union[str, None] = 'eb2bf8102413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('share_token', sa.String(length=64), nullable=True))
    op.add_column('reports', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_reports_share_token'), 'reports', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_share_token'), table_name='reports')
    op.drop_column('reports', 'is_deleted')
    op.drop_column('reports', 'share_token')
    # ### end Alembic commands ###
