"""initial_schema_users_reports_chunks_subscriptions

Revision ID: eb2bf8102413
Revises: 
Create Date: 2026-03-02 19:45:41.684797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector  # noqa: F401 — needed for VECTOR type

# revision identifiers, used by Alembic.
revision: str = 'eb2bf8102413'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Enable the pgvector extension for vector similarity search
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('reports_this_month', sa.Integer(), nullable=False),
    sa.Column('usage_reset_date', sa.Date(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reports_created_at', 'reports', ['created_at'], unique=False)
    op.create_index('idx_reports_domain', 'reports', ['domain'], unique=False)
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('report_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_domain', 'report_chunks', ['domain'], unique=False)
    # ### end Alembic commands ###

    # Create the match_report_chunks RPC function for vector similarity search
    op.execute("""
        CREATE OR REPLACE FUNCTION match_report_chunks(
            query_embedding vector(1024),
            match_count int DEFAULT 5,
            filter_domain text DEFAULT NULL,
            filter_user_id uuid DEFAULT NULL
        )
        RETURNS TABLE (
            id uuid,
            report_id uuid,
            content text,
            domain varchar(50),
            similarity float
        )
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RETURN QUERY
            SELECT
                rc.id,
                rc.report_id,
                rc.content,
                rc.domain,
                1 - (rc.embedding <=> query_embedding) AS similarity
            FROM report_chunks rc
            WHERE rc.embedding IS NOT NULL
              AND (filter_domain IS NULL OR rc.domain = filter_domain)
              AND (filter_user_id IS NULL OR rc.user_id = filter_user_id)
            ORDER BY rc.embedding <=> query_embedding
            LIMIT match_count;
        END;
        $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_domain', table_name='report_chunks')
    op.drop_table('report_chunks')
    op.drop_table('subscriptions')
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.drop_index('idx_reports_domain', table_name='reports')
    op.drop_index('idx_reports_created_at', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
